name: "Deploy lst-string-replacer"

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      #2. Build Docker image
      - name: Build Docker image
        run: docker build -t lst-string-replacer .

      #3. Save the Docker image to a file
      - name: Save image
        run: |
          DATE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          docker save nextjs-app | gzip > nextjs-app-$DATE_TAG.tar.gz

      # 4. Copy image to server
      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "lst-string-replacer-${{ env.DATE_TAG }}.tar.gz"
          target: "/opt/apps/lst-string-replacer/releases"

      # 5. Load image and run on server
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/apps/lst-string-replacer/releases
            
            # Find the newest file by datetime
            LATEST=$(ls -t lst-string-replacer-*.tar.gz | head -n1)
            echo "Deploying $LATEST"
            
            # Load image
            docker load < $LATEST
            
            # Stop old container
            docker stop lst-string-replacer || true
            docker rm lst-string-replacer || true
            
            # Run new container
            docker run -d \
              --name lst-string-replacer \
              -p 3000:3000 \
              -v /opt/apps/lst-string-replacer/data:/app/data \
              lst-string-replacer
            
            # Clean old releases, keeping only 5 newest 
            ls -t lst-string-replacer-*.tar.gz | tail -n +6 | xargs -r rm --
